services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - eis
      - app2

  eis:
    build: ./allapp1
    container_name: eis
    # environment:
      # - NODE_ENV=production
    expose:
      - "3000"

  app2:
    build: ./app2
    container_name: app2
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
